name: Release Latest

on:
  push:
    branches:
      - "master"

jobs:
  release-latest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      # - name: Install Linter
      #   run: make lint-install

      # - name: Lint
      #   run: make lint

      - name: Tests
        run: make test

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build latest image
        run: docker build --build-arg VERSION=latest -t mauriciocodeguez/coolifytest:latest .

      - name: Push latest image
        run: docker push mauriciocodeguez/coolifytest:latest

      # - name: Trigger Coolify Deploy (Latest)
      #   run: |
      #     curl -X POST "https://YOUR-COOLIFY-DOMAIN/api/v1/webhooks/deploy/${{ secrets.COOLIFY_WEBHOOK_TOKEN }}?tag=latest"
