name: Release

on:
  push:
    tags:
      - "v*"
  release:
    types: [published]

jobs:
  validate-tag:
    runs-on: ubuntu-latest

    steps:
      - run: |
          TAG="${GITHUB_REF##*/}"
          echo "TAG=$TAG" >> $GITHUB_ENV
          if [[ ! "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9.-]+)?$ ]]; then
            echo "Invalid SemVer"
            exit 1
          fi

  # lint:
  #   runs-on: ubuntu-latest
  #   needs: validate

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-go@v4
  #       with:
  #         go-version: "1.22"
  #         cache: true
  #     - run: make lint-install
  #     - run: make lint

  test:
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          cache: true
      - run: make test

  docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/setup-buildx-action@v3

      - name: Build & Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            VERSION=${{ env.TAG }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: mauriciocodeguez/coolifytest:${{ env.TAG }}

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: docker

  #   steps:
  #     - name: Trigger Coolify Deploy
  #       run: |
  #         curl -X POST "https://YOUR-COOLIFY/api/v1/webhooks/deploy/${{ secrets.COOLIFY_WEBHOOK_TOKEN }}?tag=${{ env.TAG }}"

  # release:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Extract tag
  #       id: vars
  #       run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

  #     - name: Validate SemVer
  #       run: |
  #         TAG=${TAG#v}
  #         if [[ ! "$TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.-]+)?$ ]]; then
  #           echo "‚ùå Invalid SemVer tag. Use vMAJOR.MINOR.PATCH or vMAJOR.MINOR.PATCH-prerelease"
  #           exit 1
  #         fi
  #       env:
  #         TAG: ${{ env.TAG }}

  #     - name: Install Go
  #       uses: actions/setup-go@v4
  #       with:
  #         go-version: 1.22

  #     # - name: Install Linter
  #     #   run: make lint-install

  #     # - name: Run Lint
  #     #   run: make lint

  #     - name: Run Tests
  #       run: make test

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Build image
  #       run: docker build -t mauriciocodeguez/coolifytest:${{ github.ref_name }} .

  #     - name: Push image
  #       run: docker push mauriciocodeguez/coolifytest:${{ github.ref_name }}

      # - name: Trigger Coolify Deploy (Tag)
      #   run: |
      #     curl -X POST "https://YOUR-COOLIFY-DOMAIN/api/v1/webhooks/deploy/${{ secrets.COOLIFY_WEBHOOK_TOKEN }}?tag=${{ env.TAG }}"
