name: Release

on:
  push:
    tags:
      - "v*"
  release:
    types: [published]

jobs:
  validate-tag:
    runs-on: ubuntu-latest

    steps:
      - run: |
          TAG="${GITHUB_REF##*/}"
          echo "TAG=$TAG" >> $GITHUB_ENV
          if [[ ! "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9.-]+)?$ ]]; then
            echo "Invalid SemVer"
            exit 1
          fi

  lint-test:
    runs-on: ubuntu-latest
    needs: validate-tag

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          cache: true
      # - run: make lint-install
      # - run: make lint
      - run: make test

  docker:
    runs-on: ubuntu-latest
    needs: lint-test

    steps:
      - uses: actions/checkout@v3
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: docker build -t ${{vars.DOCKER_IMAGE_NAME}}:${{ github.ref_name }} .

      - name: Push image
        run: docker push ${{vars.DOCKER_IMAGE_NAME}}:${{ github.ref_name }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Update TAG
        run: |
          curl --location --request PATCH '${{vars.COOLIFY_URL}}/api/v1/applications/${{vars.COOLIFY_RESOURCE_ID}}' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ secrets.COOLIFY_API_BEARER_TOKEN }}' \
          --data '{
              "docker_registry_image_tag": "${{ github.ref_name }}"
          }'

      - name: Trigger Coolify Deploy
        run: |
          curl --location '${{vars.COOLIFY_URL}}/api/v1/deploy?uuid=${{vars.COOLIFY_RESOURCE_ID}}&force=false' \
          --header 'Authorization: Bearer ${{ secrets.COOLIFY_API_BEARER_TOKEN }}'
